title: Software Design | Fall 2017
description: An introduction to software design.
timezone: America/New_York

collections:
  assignments:
    output: true
    layout: default
    title: Assignments
    permalink: assignments/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: files
    values:
      layout: handout

plugins:
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - config
  - scripts
  - vendor
