title: Software Design | Fall 2017
description: An introduction to software design.
timezone: America/New_York
calendar_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRJGhlctkwfwPHcEQ9H_sIML5rezTEDtDIgsTZyq4dlARZmKvGP-NTWJqu9zN1huDfpKMJQvAcYwmCq/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false"

collections:
  assignments:
    output: true
    layout: default
    title: Assignments
    permalink: assignments/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: files
    values:
      layout: handout

plugins:
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - config
  - scripts
  - vendor
