title: Software Design | Fall 2017
description: An introduction to software design.

collections:
  assignments:
    output: true
    layout: default
    title: Assignments
    permalink: assignments/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: files
    values:
      layout: null

plugins:
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - vendor
